// 16-bit-style sprites drawn programmatically. Each sprite is a 2D array of color
// indices into a small palette. We render them via tiny rects on a low-res canvas
// then upscale with image-rendering: pixelated.

export const PALETTE = {
  '.': null,           // transparent
  'k': '#0a0709',      // outline / hair
  'd': '#3a1a0e',      // dark skin shadow
  's': '#a85a3c',      // skin midtone
  'h': '#e0a07a',      // skin highlight
  'r': '#c9162b',      // red glove / mongkhon
  'R': '#7a0d1c',      // dark red
  'b': '#1d3b8a',      // blue trunks
  'B': '#0e1f4a',      // dark blue
  'g': '#d6c270',      // gold trim
  'w': '#f3e9c6',      // bone white
  'y': '#f7d24a',      // yellow flash
  'o': '#ff8d2a',      // orange impact
  'p': '#5a2a3c',      // bruise purple
  'q': '#8a3a52',      // bruise mid
  'l': '#28140e',      // shadow under fighter
  'c': '#7a4632',      // canvas/ring tan
  'm': '#221018',      // ring darkness
}

// Helper: parse a sprite string into a 2D array of indices.
// Each row separated by '\n', each char one pixel.
export function parseSprite(str) {
  return str.replace(/^\n/, '').replace(/\n$/, '').split('\n').map((row) => row.split(''))
}

// =========================================================================
// OPPONENT — full-body, 56x96 pixels, four states: idle, telegraph, strike, hit.
// He's centered in screen at moderate distance. Muay Thai: red trunks, mongkhon
// on head when entering the ring (shown briefly).
// =========================================================================

const op_idle = `
......................kkkkkkkk..........................
....................kkddddddddkk........................
...................kdsshhhssddhk........................
..................kdshhhhwhhsskhk.......................
..................kdshhwwwwhhsdhk.......................
..................kdshhhhhhhhsskk.......................
...................kdshhhhhhsdkk........................
....................kksskkdsskk.........................
......................kkkkkkk...........................
.....................kkddddkk...........................
....................kdssssssdk..........................
...................kdshhhhhhsdk.........................
..................kdshhwwwwwhhsdk........................
.................kdshhwwwwwwwhhsdk.......................
................kdshhwwwwwwwwwhhsdk......................
...............kdshhwwwwwwwwwwwhhsdk.....................
..............kdshhwwwwwwwwwwwwwhhsdk....................
..............kdsshhwwwwwwwwwwwhhssdk....................
..............kddssshhwwwwwwwhhssddkk....................
.............kRrrkddssshhhhhhssddkkrRk...................
............kRrrrkkkkddddddddkkkkrrrRk..................
...........kRrrrrrrkkkkkkkkkkkkrrrrrrRk.................
...........kRrrrrrrrrrrrrrrrrrrrrrrrrRk.................
...........kRrrrrrrrrrrrrrrrrrrrrrrrrRk.................
............kRrrrrrrrrrrrrrrrrrrrrrrRk..................
.............kRRrrrrrrrrrrrrrrrrrrrRRk..................
..............kkRRRrrrrrrrrrrrrrrRRRkk...................
................kkRRrrrrrrrrrrrrRRkk.....................
..................ksshhhhhhhhhhsskk......................
..................kdshhhhhhhhhhsdkk......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdsbbbbbbbbbbsdk.......................
.................kdsbbbbbbbbbbbbsdk......................
................kdsbBBbgggggggBBbsdk.....................
................kdsbBgggggggggggBbsdk....................
................kdsbBgggggggggggBbsdk....................
................kdsbBBbgggggggBBbsdk.....................
................kdsbbbbbbbbbbbbbbsdk.....................
................kdshhhhhhhhhhhhhhsdk.....................
................kdshhhhhhhhhhhhhhsdk.....................
................kdsdddddhhhhdddddsdk.....................
...............kdsddkkkkdhhdkkkkddsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
................kdshhhdhhhdhhhhhhsdk.....................
................kdshhhdhhhdhhhhhhsdk.....................
................kdsshhdhhhdhhhhhssdk.....................
.................kddssdhhhdsssddkk.......................
................kddkkkkdhhdkkkkddk.......................
................klllllldhhdllllllk.......................
`

const op_tele_jab = `
......................kkkkkkkk..........................
....................kkddddddddkk........................
...................kdsshhhssddhk........................
..................kdshhhhwhhsskhk.......................
..................kdshhwwwwhhsdhk.......................
..................kdshhhhhhhhsskk.......................
...................kdshhhhhhsdkk........................
....................kksskkdsskk.........................
......................kkkkkkk...........................
.....................kkddddkk...........................
....................kdssssssdk..........................
...................kdshhhhhhsdk.........................
..................kdshhwwwwwhhsdk........................
.................kdshhwwwwwwwhhsdk.......................
................kdshhwwwwwwwwwhhsdk......................
...............kdshhwwwwwwwwwwwhhsdk.....................
..............kdshhwwwwwwwwwwwwwhhsdk....................
..............kdsshhwwwwwwwwwwwhhssdk....................
..............kddssshhwwwwwwwhhssddk.....................
.............kRrrkddssshhhhhhssddkk......................
............kRrrrkkkkddddddddkkkk........................
...........kRrrrrrrkkkkkkkkkkkk..........................
...........kRrrrrrrrrrrrrrrrrkkkkkkk.....................
...........kRrrrrrrrrrrrrrrrrkrrrrrrkkk..................
............kRrrrrrrrrrrrrrrrkrrrrrrrrrkk................
.............kRRrrrrrrrrrrrrrkRrrrrrrrrrRk...............
..............kkRRRrrrrrrrrrrkRRrrrrrrrrRRk..............
................kkRRrrrrrrrrrkkRRrrrrrrrRRk..............
..................ksshhhhhhhhsskRRrrrrrRRk...............
..................kdshhhhhhhhhsdkkRRrRRRkk...............
..................kdshhhhhhhhhhsdkkkkkkk.................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdsbbbbbbbbbbsdk.......................
.................kdsbbbbbbbbbbbbsdk......................
................kdsbBBbgggggggBBbsdk.....................
................kdsbBgggggggggggBbsdk....................
................kdsbBgggggggggggBbsdk....................
................kdsbBBbgggggggBBbsdk.....................
................kdsbbbbbbbbbbbbbbsdk.....................
................kdshhhhhhhhhhhhhhsdk.....................
................kdshhhhhhhhhhhhhhsdk.....................
................kdsdddddhhhhdddddsdk.....................
...............kdsddkkkkdhhdkkkkddsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
................kdshhhdhhhdhhhhhhsdk.....................
................kdshhhdhhhdhhhhhhsdk.....................
................kdsshhdhhhdhhhhhssdk.....................
.................kddssdhhhdsssddkk.......................
................kddkkkkdhhdkkkkddk.......................
................klllllldhhdllllllk.......................
`

// Right cross fully extended (right hand from his POV = left side of his body).
// Big glove pushed forward toward the camera — render slightly larger.
const op_strike_cross = `
......................kkkkkkkk..........................
....................kkddddddddkk........................
...................kdsshhhssddhk........................
..................kdshhhhwhhsskhk.......................
..................kdshhwwwwhhsdhk.......................
..................kdshhhhhhhhsskk.......................
...................kdshhhhhhsdkk........................
....................kksskkdsskk.........................
......................kkkkkkk...........................
.....................kkddddkk...........................
....................kdssssssdk..........................
...................kdshhhhhhsdk.........................
.................kdshhwwwwwhhsdk.........................
................kdshhwwwwwwwhhsdk........................
...............kdshhwwwwwwwwwhhsdk.......................
..............kdshhwwwwwwwwwwwhhsdk......................
.............kdshhwwwwwwwwwwwwwhhsdk.....................
..............kdsshhwwwwwwwwwwwhhssdk....................
......kkkkkk..kddssshhwwwwwwwhhssddk.....................
....kkRRRRRRkkkddssshhhhhhssddkk.........................
...kRrrrrrrrRRkkddddddddkkkk.............................
..kRrrrrrrrrrrRkkkkkkkkkk................................
..kRrrrrrrrrrrrRk........................................
..kRrrrrrrrrrrrRk........................................
...kRrrrrrrrrrRk.........................................
....kkRRrrrrRRkk.........................................
......kkkRRkkk...........................................
.................ksskk...................................
..................ksshhhhhhhhhhsskk......................
..................kdshhhhhhhhhhsdkk......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdsbbbbbbbbbbsdk.......................
.................kdsbbbbbbbbbbbbsdk......................
................kdsbBBbgggggggBBbsdk.....................
................kdsbBgggggggggggBbsdk....................
................kdsbBgggggggggggBbsdk....................
................kdsbBBbgggggggBBbsdk.....................
................kdsbbbbbbbbbbbbbbsdk.....................
................kdshhhhhhhhhhhhhhsdk.....................
................kdshhhhhhhhhhhhhhsdk.....................
................kdsdddddhhhhdddddsdk.....................
...............kdsddkkkkdhhdkkkkddsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
................kdshhhdhhhdhhhhhhsdk.....................
................kdshhhdhhhdhhhhhhsdk.....................
................kdsshhdhhhdhhhhhssdk.....................
.................kddssdhhhdsssddkk.......................
................kddkkkkdhhdkkkkddk.......................
................klllllldhhdllllllk.......................
`

// Right roundhouse kick — leg cocked high to the right, shin coming in.
const op_strike_kick = `
......................kkkkkkkk..........................
....................kkddddddddkk........................
...................kdsshhhssdsskk.......................
..................kdshhhhhhhhsdhk.......................
..................kdshhhhhhhhsdhk.......................
..................kdshhhwwwhhsskk.......................
...................kdshhhhhhsdkk........................
....................kksskkdsskk.........................
......................kkkkkkk...........................
.....................kkddddkk...........................
....................kdssssssdk..........................
...................kdshhhhhhsdk.........................
..................kdshhwwwwwhhsdk........................
.................kdshhwwwwwwwhhsdk.......................
................kdshhwwwwwwwwwhhsdk......................
...............kdshhwwwwwwwwwwwhhsdk.....................
..............kdshhwwwwwwwwwwwwwhhsdk....................
..............kdsshhwwwwwwwwwwwhhssdk....................
..............kddssshhwwwwwwwhhssddkk....................
.............kRrrkddssshhhhhhssddkkrRk...................
............kRrrrkkkkddddddddkkkkrrrRk..................
...........kRrrrrrrkkkkkkkkkkkkrrrrrrRk.................
...........kRrrrrrrrrrrrrrrrrrrrrrrrrRk.................
...........kRrrrrrrrrrrrrrrrrrrrrrrrrRk.................
............kRrrrrrrrrrrrrrrrrrrrrrrRk..................
.............kRRrrrrrrrrrrrrrrrrrrrRRk..................
..............kkRRRrrrrrrrrrrrrrrRRRkk...................
................kkRRrrrrrrrrrrrrRRkk.....................
..................ksshhhhhhhhhhsskk......................
..................kdshhhhhhhhhhsdkk......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdsbbbbbbbbbbsdk.......................
.................kdsbbbbbbbbbbbbsdk......................
................kdsbBBbgggggggBBbsdk.....................
................kdsbBgggggggggggBbsdk....................
................kdsbBgggggggggggBbsdk...kkkkk............
................kdsbBBbgggggggBBbsdkkkkdsssdkk...........
................kdsbbbbbbbbbbbbbbsdkkdshhhhsdk...........
................kdshhhhhhhhhhhhhhsdkdshhhhhhsdk..........
................kdshhhhhhhhhhhhhhsdkdshhhhhhsdk..........
................kdsdddddhhhhdddddsdkdshhhhhhsdk..........
...............kdsddkkkkdhhdkkkkddsdkdshhhhhhsdk.........
...............kdshhhhhdhhhhhhhhhhsdkdshhhhhhsdk.........
...............kdshhhhhdhhhhhhhhhhsdkdshhhhhhsdk.........
...............kdshhhhhdhhhhhhhhhhsdkdshhhhhhsdk.........
...............kdshhhhhdhhhhhhhhhhsdkdshhhhhhsdk.........
................kdshhhdhhhdhhhhhhsdkkdshhhhhsdk.........
................kdshhhdhhhdhhhhhhsdkkkdsshhsdkk..........
................kdsshhdhhhdhhhhhssdkkkkdssdkkk...........
.................kddssdhhhdsssddkkkkkkkkdkkk.............
................kddkkkkdhhdkkkkddk.......................
................klllllldhhdllllllk.......................
`

// Hit reaction — head snapped back, slight blood streak.
const op_hit = `
......................kkkkkkkk..........................
....................kkddddddyykk........................
...................kdsshhyyywwwk........................
..................kdshhhhwwwyywyk.......................
..................kdshhwwowwhhsdyk......................
..................kdshhhhhhhhsskk.......................
...................kdshhrhhhsdkk........................
....................kksRkkdsskk.........................
......................kkkRkkk...........................
.....................kkddRdkk............................
....................kdssssssdk..........................
...................kdshhhhhhsdk.........................
..................kdshhwwwwwhhsdk........................
.................kdshhwwwwwwwhhsdk.......................
................kdshhwwwwwwwwwhhsdk......................
...............kdshhwwwwwwwwwwwhhsdk.....................
..............kdshhwwwwwwwwwwwwwhhsdk....................
..............kdsshhwwwwwwwwwwwhhssdk....................
..............kddssshhwwwwwwwhhssddkk....................
.............kRrrkddssshhhhhhssddkkrRk...................
............kRrrrkkkkddddddddkkkkrrrRk..................
...........kRrrrrrrkkkkkkkkkkkkrrrrrrRk.................
...........kRrrrrrrrrrrrrrrrrrrrrrrrrRk.................
...........kRrrrrrrrrrrrrrrrrrrrrrrrrRk.................
............kRrrrrrrrrrrrrrrrrrrrrrrRk..................
.............kRRrrrrrrrrrrrrrrrrrrrRRk..................
..............kkRRRrrrrrrrrrrrrrrRRRkk...................
................kkRRrrrrrrrrrrrrRRkk.....................
..................ksshhhhhhhhhhsskk......................
..................kdshhhhhhhhhhsdkk......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdsbbbbbbbbbbsdk.......................
.................kdsbbbbbbbbbbbbsdk......................
................kdsbBBbgggggggBBbsdk.....................
................kdsbBgggggggggggBbsdk....................
................kdsbBgggggggggggBbsdk....................
................kdsbBBbgggggggBBbsdk.....................
................kdsbbbbbbbbbbbbbbsdk.....................
................kdshhhhhhhhhhhhhhsdk.....................
................kdshhhhhhhhhhhhhhsdk.....................
................kdsdddddhhhhdddddsdk.....................
...............kdsddkkkkdhhdkkkkddsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
...............kdshhhhhdhhhhhhhhhhsdk....................
................kdshhhdhhhdhhhhhhsdk.....................
................kdshhhdhhhdhhhhhhsdk.....................
................kdsshhdhhhdhhhhhssdk.....................
.................kddssdhhhdsssddkk.......................
................kddkkkkdhhdkkkkddk.......................
................klllllldhhdllllllk.......................
`

// Knee strike — one knee raised high, body coiled inward
const op_strike_knee = `
......................kkkkkkkk..........................
....................kkddddddddkk........................
...................kdsshhhssddhk........................
..................kdshhhhwhhsskhk.......................
..................kdshhwwwwhhsdhk.......................
..................kdshhhhhhhhsskk.......................
...................kdshhhhhhsdkk........................
....................kksskkdsskk.........................
......................kkkkkkk...........................
.....................kkddddkk...........................
....................kdssssssdk..........................
...................kdshhhhhhsdk.........................
..................kdshhwwwwwhhsdk........................
.................kdshhwwwwwwwhhsdk.......................
................kdshhwwwwwwwwwhhsdk......................
...............kdshhwwwwwwwwwwwhhsdk.....................
..............kdshhwwwwwwwwwwwwwhhsdk....................
..............kdsshhwwwwwwwwwwwhhssdk....................
..............kddssshhwwwwwwwhhssddkk....................
.............kRrrkddssshhhhhhssddkkrRk...................
............kRrrrkkkkddddddddkkkkrrrRk..................
...........kRrrrrrrkkkkkkkkkkkkrrrrrrRk.................
...........kRrrrrrrrrrrrrrrrrrrrrrrrrRk.................
...........kRrrrrrrrrrrrrrrrrrrrrrrrrRk.................
............kRrrrrrrrrrrrrrrrrrrrrrrRk..................
.............kRRrrrrrrrrrrrrrrrrrrrRRk..................
..............kkRRRrrrrrrrrrrrrrrRRRkk...................
................kkRRrrrrrrrrrrrrRRkk.....................
..................ksshhhhhhhhhhsskk......................
..................kdshhhhhhhhhhsdkk......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdshhhhhhhhhhsdk.......................
..................kdsbbbbbbbbbbsdk.......................
.................kdsbbbbbbbbbbbbsdk......................
................kdsbBBbgggggggBBbsdk.....................
................kdsbBgggggggggggBbsdk....................
................kdsbBgggggggggggBbsdk....................
................kdsbBBbgggggggBBbsdk.....................
................kdsbbbbbbbbbbbbbbsdk.....................
................kdshhhhhhhhhhhhhhsdk.....................
................kdshhhhhhhhhhhhhhsdk.....................
................kdsdddddhhhhdddddsdk.....................
...............kdsddkkkkdhhdkkkkddsdk....................
...............kdshhhhhdhhdhhhhhhsdk.....................
...............kdshhhhhdhhdhhhhhhsdk.....................
...............kdshhhhdshhdhhhhhhsdk.....................
..............kdshhhhddhhhdhhhhhhsdk.....................
.............kdshhhhdsdhhhdhhhhhhsdk.....................
............kdshhhhhdshhhhdhhhhhhsdk.....................
...........kdsshhhhdshhhhhdhhhhhssdk.....................
..........kddsshhhhdshhhhhdsssddkk.......................
.........kddkkkdhhhdshhhhhdkkkkddk.......................
.........klllllldhhdshhhhhdllllllk.......................
`

// Block stance — both gloves up high in front of face
const op_block = `
......................kkkkkkkk..........................
....................kkddddddddkk........................
....................kdshhhhhhsdk.........................
....................kdshhhhhhsdk.........................
....................kdshhhhhhsdk.........................
.....................kkddddddkk..........................
.................kkrRRRkkkkkRRRrkk........................
................kRrrrrkkkkkkkkrrrrRk......................
...............kRrrrrrkkkkkkkkrrrrrRk.....................
..............kRrrrrrrkkkkkkkkrrrrrrRk....................
.............kRrrrrrrrkkkkkkkkrrrrrrrRk...................
.............kRrrrrrrrkkkkkkkkrrrrrrrRk...................
..............kRrrrrrrkkkkkkkkrrrrrrRk....................
...............kRrrrrrkkkkkkkkrrrrrRk.....................
................kkRRrrkkkkkkkkrrRRkk......................
..................kkRRkkkkkkkkRRkk........................
.....................kkkkkkkkkk...........................
.....................kkkkkkkkkk...........................
....................kdsssssssssdk.........................
...................kdshhhhhhhhhhsdk.......................
..................kdshhwwwwwwwwhhsdk......................
..................kdshhwwwwwwwwhhsdk......................
..................kdshhhhhhhhhhhhsdk......................
..................kdshhhhhhhhhhhhsdk......................
..................kdshhhhhhhhhhhhsdk......................
..................kdshhhhhhhhhhhhsdk......................
..................kdshhhhhhhhhhhhsdk......................
..................kdshhhhhhhhhhhhsdk......................
..................kdshhhhhhhhhhhhsdk......................
..................kdshhhhhhhhhhhhsdk......................
..................kdshhhhhhhhhhhhsdk......................
..................kdshhhhhhhhhhhhsdk......................
..................kdshhhhhhhhhhhhsdk......................
..................kdshhhhhhhhhhhhsdk......................
..................kdshhhhhhhhhhhhsdk......................
..................kdsbbbbbbbbbbbbsdk......................
.................kdsbbbbbbbbbbbbbbsdk.....................
................kdsbBBbgggggggBBbsdk......................
................kdsbBgggggggggggBbsdk.....................
................kdsbBgggggggggggBbsdk.....................
................kdsbBBbgggggggBBbsdk......................
................kdsbbbbbbbbbbbbbbsdk......................
................kdshhhhhhhhhhhhhhsdk......................
................kdshhhhhhhhhhhhhhsdk......................
................kdsdddddhhhhdddddsdk......................
...............kdsddkkkkdhhdkkkkddsdk.....................
...............kdshhhhhdhhhhhhhhhhsdk.....................
...............kdshhhhhdhhhhhhhhhhsdk.....................
...............kdshhhhhdhhhhhhhhhhsdk.....................
...............kdshhhhhdhhhhhhhhhhsdk.....................
................kdshhhdhhhdhhhhhhsdk......................
................kdshhhdhhhdhhhhhhsdk......................
................kdsshhdhhhdhhhhhssdk......................
.................kddssdhhhdsssddkk........................
................kddkkkkdhhdkkkkddk........................
................klllllldhhdllllllk........................
`

export const opponentSprites = {
  idle: parseSprite(op_idle),
  tele_jab: parseSprite(op_tele_jab),
  strike_cross: parseSprite(op_strike_cross),
  strike_kick: parseSprite(op_strike_kick),
  strike_knee: parseSprite(op_strike_knee),
  block: parseSprite(op_block),
  hit: parseSprite(op_hit),
}

// =========================================================================
// PLAYER FOREGROUND — bottom-of-screen translucent shoulders + gloves.
// Two gloves visible left/right, drawn at gloves's idle / extended states.
// =========================================================================

const glove_idle = `
....kRrrrrrrrRk....
...kRrrrrrrrrrRk...
..kRrrrrrrrrrrrRk..
.kRrrrrrrrrrrrrrRk.
.kRrrrrrrrrrrrrrRk.
.kRrrrrrrrrrrrrrRk.
.kRrrwwrrrrrrrrrRk.
.kRrwwhwrrrrrrrrRk.
.kRrwhhwrrrrrrrrRk.
.kRrwwwwrrrrrrrrRk.
.kRrrrrrrrrrrrrrRk.
.kRrrrrrrrrrrrrrRk.
.kRrrrrrrrrrrrrrRk.
..kRrrrrrrrrrrrRk..
...kRrrrrrrrrrRk...
....kRRrrrrrrRRk...
.....kkRRrrRRkk....
.......kkRRkk......
`

// Player jab in motion - glove pulled back slightly
const glove_jab_back = `
....kRrrrrrrrRk....
...kRrrrrrrrrrRk...
..kRrrrrrrrrrrrRk..
.kRrrrrrrrrrrrrrRk.
.kRrrrrrrrrrrrrrRk.
.kRrrrrrrrrrrrrrRk.
.kRrrrrrrrrrrrrrRk.
.kRrrrrrrrrrrrrrRk.
.kRrrwwwwwrrrrrrRk.
.kRrwwhhhwrrrrrrRk.
.kRwwhhhhhwrrrrrRk.
.kRwhhhhhhhwrrrrRk.
.kRwhwwwwwhwrrrrRk.
.kRwwwwwwwwwrrrrRk.
..kRrrrrrrrrrrrRk..
...kRrrrrrrrrrRk...
....kRRrrrrrrRRk...
.....kkRRrrRRkk....
`

export const gloveSprites = {
  idle: parseSprite(glove_idle),
  jab_back: parseSprite(glove_jab_back),
}

// =========================================================================
// HEAD/SHOULDERS silhouette (translucent foreground, drawn very bottom).
// Just a dark silhouette of the back of the head + tops of shoulders.
// =========================================================================

export const playerSilhouette = parseSprite(`
.....................kkkkkkkkkkkkkkkkkk......................
....................kklllllllllllllllllkk....................
...................kllllllllllllllllllllllk..................
..................klllllllllllllllllllllllllk................
.................kllllllllllllllllllllllllllllk..............
................klllllllllllllllllllllllllllllllk............
...............kllllllllllllllllllllllllllllllllllk..........
...............kllllllllllllllllllllllllllllllllllk..........
..............kllllllllllllllllllllllllllllllllllllk.........
.............kllllllllllllllllllllllllllllllllllllllk........
............kllllllllllllllllllllllllllllllllllllllllk.......
...........kllllllllllllllllllllllllllllllllllllllllllk......
..........kllllllllllllllllllllllllllllllllllllllllllllk.....
.........klllllllllllllllllllllllllllllllllllllllllllllllk...
........klllllllllllllllllllllllllllllllllllllllllllllllllk..
.......kllllllllllllllllllllllllllllllllllllllllllllllllllllk
......klllllllllllllllllllllllllllllllllllllllllllllllllllllk
`)
